import { 
  fetchTrendingMovies, 
  fetchUpComingMovies, 
  fetchTopRatedMovies,
  fetchMovieDetails,
  fetchMovieCredits,
  fetchSimilarMovies,
  fetchRecommendedMovies,
  fetchPersonDetails,
  fetchPersonMovieDetails,
  fetchSearchedMovies,
  image185,
  image342,
  image500,
  imageOriginal,
  fallbackPersonImage,
  fallbackPosterImage,
 } from '../../api/movieService';

export {
  fetchTrendingMovies, 
  fetchUpComingMovies, 
  fetchTopRatedMovies,
  fetchMovieDetails,
  fetchMovieCredits,
  fetchSimilarMovies,
  fetchRecommendedMovies,
  fetchPersonDetails,
  fetchPersonMovieDetails,
  fetchSearchedMovies,
  image185,
  image342,
  image500,
  imageOriginal,
  fallbackPersonImage,
  fallbackPosterImage,
};